### ISSUE TITLE
example game client doesn't work

### ISSUE THREAD

**Issue by asonix** [jaybutera/mmo-rust-server#2]
In both Firefox and Epiphany, I get the following error when running the game client. The number of occurrences increases rapidly in both browsers.

![image](https://user-images.githubusercontent.com/5304643/51047900-4134d980-158f-11e9-9ab9-cd3f3a0c5565.png)

**Comment by jaybutera** [comment]
What version of Firefox? I'm running Quantum 64.0.2 and forEach seems to be supported.

**Comment by jaybutera** [comment]
Updated the for loop, should work now.

**Comment by asonix** [comment]
it may have been something I've done. I'm poking this project a lot right now
